// Static search index for the wiki search bar (client-side, no dependencies).
//
// Provenance & rules:
// - Page entries are derived from `src/pages.ts` (name, title, path, group, lead).
// - Section entries are derived by reading every `src/contents/*.tsx` file: each
//   `PageSection` contributes its `title`; its `eyebrow` words go into keywords.
//   The two `CitationList` sections ("References and evidence", rendered as a
//   real <section> with an <h2> on Description and Problem) are included too.
// - `anchor` for every section entry equals `stringToSlug(sectionTitle)` exactly
//   as implemented in `src/utils/stringToSlug.ts` (lowercase, non [a-z0-9-] →
//   "-", collapse "-", trim ends), so deep links land on the rendered <h2>.
// - Keywords are navigational search terms only (what a judge or teammate might
//   type). They add no claims. No [TEAM CONTENT REQUIRED] placeholder text is
//   indexed anywhere in this file.
// - Keep this file serializable and dependency-free: no imports.

export interface SearchEntry {
  path: string;
  pageName: string;
  pageTitle: string;
  group?: string;
  kind: "page" | "section";
  sectionTitle?: string;
  anchor?: string;
  keywords: string[];
}

export const searchIndex: SearchEntry[] = [
  // ─── Page entries (src/pages.ts) ───────────────────────────────────────────
  {
    path: "/",
    pageName: "Home",
    pageTitle: "Strength Over Time",
    kind: "page",
    keywords: [
      "igem 2026",
      "worldshaper nanjing",
      "strength over time",
      "synthetic biology",
      "team wiki",
      "homepage",
      "start here",
      "overview",
      "age-related muscle decline",
      "project introduction",
    ],
  },
  {
    path: "/description",
    pageName: "Description",
    pageTitle: "Project Description",
    group: "Project",
    kind: "page",
    keywords: [
      "project description",
      "abstract",
      "motivation",
      "background",
      "context",
      "objectives",
      "scope",
      "research question",
      "muscle health",
      "project goals",
    ],
  },
  {
    path: "/problem",
    pageName: "Problem",
    pageTitle: "The Problem",
    group: "Project",
    kind: "page",
    keywords: [
      "sarcopenia",
      "muscle loss",
      "aging",
      "age-related muscle decline",
      "sarcopenia research gap",
      "muscle weakness",
      "prevalence",
      "problem statement",
      "risk factors",
    ],
  },
  {
    path: "/solution",
    pageName: "Solution",
    pageTitle: "Proposed Solution",
    group: "Project",
    kind: "page",
    keywords: [
      "proposed solution",
      "design concept",
      "genetic circuit",
      "biosensor",
      "chassis",
      "genetic design",
      "system architecture",
      "sensing",
      "measurable output",
      "mechanism",
    ],
  },
  {
    path: "/engineering",
    pageName: "Engineering",
    pageTitle: "Engineering",
    group: "Research",
    kind: "page",
    keywords: [
      "engineering",
      "dbtl",
      "design build test learn",
      "engineering cycle",
      "iteration",
      "engineering success",
      "decision register",
      "traceability",
      "prototype",
    ],
  },
  {
    path: "/experiments",
    pageName: "Experiments",
    pageTitle: "Experiments",
    group: "Research",
    kind: "page",
    keywords: [
      "experiments",
      "protocols",
      "methods",
      "lab procedures",
      "controls",
      "materials",
      "construct preparation",
      "characterization",
      "protocol record",
    ],
  },
  {
    path: "/notebook",
    pageName: "Notebook",
    pageTitle: "Notebook",
    group: "Research",
    kind: "page",
    keywords: [
      "notebook",
      "lab notes",
      "timeline",
      "dates",
      "chronological record",
      "decision log",
      "milestones",
      "setbacks",
      "activity log",
    ],
  },
  {
    path: "/results",
    pageName: "Results",
    pageTitle: "Results",
    group: "Research",
    kind: "page",
    keywords: [
      "results",
      "data",
      "figures",
      "analysis",
      "evidence",
      "measurements",
      "controls",
      "conclusions",
      "limitations",
      "negative results",
    ],
  },
  {
    path: "/human-practices",
    pageName: "Human Practices",
    pageTitle: "Human Practices",
    group: "People",
    kind: "page",
    keywords: [
      "human practices",
      "stakeholders",
      "interviews",
      "outreach",
      "public engagement",
      "feedback",
      "responsibility",
      "values",
      "integrated human practices",
    ],
  },
  {
    path: "/safety-and-security",
    pageName: "Safety",
    pageTitle: "Safety and Security",
    group: "People",
    kind: "page",
    keywords: [
      "safety",
      "risk",
      "biosafety",
      "lab safety",
      "biosecurity",
      "risk assessment",
      "hazards",
      "containment",
      "approvals",
      "waste management",
    ],
  },
  {
    path: "/contribution",
    pageName: "Contribution",
    pageTitle: "Contribution",
    group: "People",
    kind: "page",
    keywords: [
      "contribution",
      "parts",
      "documentation",
      "reusable resources",
      "future teams",
      "open source",
      "license",
      "datasets",
      "tools",
      "reproducibility",
    ],
  },
  {
    path: "/team",
    pageName: "Team",
    pageTitle: "Our Team",
    group: "People",
    kind: "page",
    keywords: [
      "team",
      "members",
      "captains",
      "instructors",
      "advisors",
      "roles",
      "attribution",
      "about us",
      "introductions",
    ],
  },

  // ─── Section entries (src/contents/*.tsx) ─────────────────────────────────
  // home.tsx
  {
    path: "/",
    pageName: "Home",
    pageTitle: "Strength Over Time",
    kind: "section",
    sectionTitle: "A project built around three connected questions",
    anchor: "a-project-built-around-three-connected-questions",
    keywords: ["our direction", "themes", "understand", "engineer", "integrate"],
  },
  {
    path: "/",
    pageName: "Home",
    pageTitle: "Strength Over Time",
    kind: "section",
    sectionTitle: "Follow the work from question to evidence",
    anchor: "follow-the-work-from-question-to-evidence",
    keywords: ["project record", "pathway", "problem", "solution", "engineering", "results"],
  },

  // description.tsx
  {
    path: "/description",
    pageName: "Description",
    pageTitle: "Project Description",
    group: "Project",
    kind: "section",
    sectionTitle: "Why this project?",
    anchor: "why-this-project",
    keywords: ["context", "why", "muscle health", "motivation"],
  },
  {
    path: "/description",
    pageName: "Description",
    pageTitle: "Project Description",
    group: "Project",
    kind: "section",
    sectionTitle: "Project objectives",
    anchor: "project-objectives",
    keywords: ["definition", "objectives", "research question", "technical objective"],
  },
  {
    path: "/description",
    pageName: "Description",
    pageTitle: "Project Description",
    group: "Project",
    kind: "section",
    sectionTitle: "What is—and is not—being claimed",
    anchor: "what-is-and-is-not-being-claimed",
    keywords: ["boundaries", "claims", "limitations", "project status"],
  },
  {
    path: "/description",
    pageName: "Description",
    pageTitle: "Project Description",
    group: "Project",
    kind: "section",
    sectionTitle: "References and evidence",
    anchor: "references-and-evidence",
    keywords: ["citations", "references", "sources"],
  },

  // problem.tsx
  {
    path: "/problem",
    pageName: "Problem",
    pageTitle: "The Problem",
    group: "Project",
    kind: "section",
    sectionTitle: "Muscle health changes across a lifetime",
    anchor: "muscle-health-changes-across-a-lifetime",
    keywords: ["the challenge", "human context", "biological context", "existing approaches"],
  },
  {
    path: "/problem",
    pageName: "Problem",
    pageTitle: "The Problem",
    group: "Project",
    kind: "section",
    sectionTitle: "A source-backed narrative, not an invented timeline",
    anchor: "a-source-backed-narrative-not-an-invented-timeline",
    keywords: ["progression", "stages", "risk factors", "timeline"],
  },
  {
    path: "/problem",
    pageName: "Problem",
    pageTitle: "The Problem",
    group: "Project",
    kind: "section",
    sectionTitle: "The question our team can test",
    anchor: "the-question-our-team-can-test",
    keywords: ["research gap", "testable question", "focus statement"],
  },
  {
    path: "/problem",
    pageName: "Problem",
    pageTitle: "The Problem",
    group: "Project",
    kind: "section",
    sectionTitle: "References and evidence",
    anchor: "references-and-evidence",
    keywords: ["citations", "references", "sources"],
  },

  // solution.tsx
  {
    path: "/solution",
    pageName: "Solution",
    pageTitle: "Proposed Solution",
    group: "Project",
    kind: "section",
    sectionTitle: "From sensing to a measurable output",
    anchor: "from-sensing-to-a-measurable-output",
    keywords: ["design concept", "input", "sensing", "processing", "output", "validation"],
  },
  {
    path: "/solution",
    pageName: "Solution",
    pageTitle: "Proposed Solution",
    group: "Project",
    kind: "section",
    sectionTitle: "Proposed components",
    anchor: "proposed-components",
    keywords: ["system", "chassis", "genetic design", "architecture", "expected behavior"],
  },
  {
    path: "/solution",
    pageName: "Solution",
    pageTitle: "Proposed Solution",
    group: "Project",
    kind: "section",
    sectionTitle: "How the concept will be tested",
    anchor: "how-the-concept-will-be-tested",
    keywords: ["evaluation", "testing", "success criterion", "measurement"],
  },

  // engineering.tsx
  {
    path: "/engineering",
    pageName: "Engineering",
    pageTitle: "Engineering",
    group: "Research",
    kind: "section",
    sectionTitle: "Engineering design cycle",
    anchor: "engineering-design-cycle",
    keywords: ["cycle 01", "design", "build", "test", "learn"],
  },
  {
    path: "/engineering",
    pageName: "Engineering",
    pageTitle: "Engineering",
    group: "Research",
    kind: "section",
    sectionTitle: "Decision and evidence register",
    anchor: "decision-and-evidence-register",
    keywords: ["traceability", "decisions", "register", "iterations"],
  },
  {
    path: "/engineering",
    pageName: "Engineering",
    pageTitle: "Engineering",
    group: "Research",
    kind: "section",
    sectionTitle: "What the team will change",
    anchor: "what-the-team-will-change",
    keywords: ["next iteration", "design change", "lessons learned"],
  },

  // experiments.tsx
  {
    path: "/experiments",
    pageName: "Experiments",
    pageTitle: "Experiments",
    group: "Research",
    kind: "section",
    sectionTitle: "Experiments and methods",
    anchor: "experiments-and-methods",
    keywords: ["protocol index", "construct preparation", "system characterization", "functional evaluation"],
  },
  {
    path: "/experiments",
    pageName: "Experiments",
    pageTitle: "Experiments",
    group: "Research",
    kind: "section",
    sectionTitle: "Protocol record",
    anchor: "protocol-record",
    keywords: ["reproducibility", "materials", "controls", "register"],
  },
  {
    path: "/experiments",
    pageName: "Experiments",
    pageTitle: "Experiments",
    group: "Research",
    kind: "section",
    sectionTitle: "What every protocol must include",
    anchor: "what-every-protocol-must-include",
    keywords: ["documentation", "checklist", "versioning", "risk assessment"],
  },

  // notebook.tsx
  {
    path: "/notebook",
    pageName: "Notebook",
    pageTitle: "Notebook",
    group: "Research",
    kind: "section",
    sectionTitle: "Decisions over time",
    anchor: "decisions-over-time",
    keywords: ["season record", "project definition", "milestone", "revision"],
  },
  {
    path: "/notebook",
    pageName: "Notebook",
    pageTitle: "Notebook",
    group: "Research",
    kind: "section",
    sectionTitle: "Notebook entry register",
    anchor: "notebook-entry-register",
    keywords: ["index", "entries", "dates", "evidence links"],
  },

  // results.tsx
  {
    path: "/results",
    pageName: "Results",
    pageTitle: "Results",
    group: "Research",
    kind: "section",
    sectionTitle: "Results at a glance",
    anchor: "results-at-a-glance",
    keywords: ["evidence", "build verification", "characterization", "functional test"],
  },
  {
    path: "/results",
    pageName: "Results",
    pageTitle: "Results",
    group: "Research",
    kind: "section",
    sectionTitle: "Figures and analysis",
    anchor: "figures-and-analysis",
    keywords: ["data", "figures", "primary result", "control comparison"],
  },
  {
    path: "/results",
    pageName: "Results",
    pageTitle: "Results",
    group: "Research",
    kind: "section",
    sectionTitle: "Claims mapped to evidence",
    anchor: "claims-mapped-to-evidence",
    keywords: ["interpretation", "observations", "conclusions", "limitations"],
  },
  {
    path: "/results",
    pageName: "Results",
    pageTitle: "Results",
    group: "Research",
    kind: "section",
    sectionTitle: "What failed and what comes next",
    anchor: "what-failed-and-what-comes-next",
    keywords: ["reflection", "negative results", "next experiment"],
  },

  // human-practices.tsx
  {
    path: "/human-practices",
    pageName: "Human Practices",
    pageTitle: "Human Practices",
    group: "People",
    kind: "section",
    sectionTitle: "How the world shapes the project",
    anchor: "how-the-world-shapes-the-project",
    keywords: ["responsibility", "values", "stakeholders", "responsiveness"],
  },
  {
    path: "/human-practices",
    pageName: "Human Practices",
    pageTitle: "Human Practices",
    group: "People",
    kind: "section",
    sectionTitle: "Engage, learn, change, revisit",
    anchor: "engage-learn-change-revisit",
    keywords: ["integration", "engage", "learn", "change", "revisit"],
  },
  {
    path: "/human-practices",
    pageName: "Human Practices",
    pageTitle: "Human Practices",
    group: "People",
    kind: "section",
    sectionTitle: "Feedback-to-design matrix",
    anchor: "feedback-to-design-matrix",
    keywords: ["matrix", "stakeholder groups", "learning", "follow-up"],
  },

  // safety-and-security.tsx
  {
    path: "/safety-and-security",
    pageName: "Safety",
    pageTitle: "Safety and Security",
    group: "People",
    kind: "section",
    sectionTitle: "Identify hazards before work begins",
    anchor: "identify-hazards-before-work-begins",
    keywords: ["safety by design", "biological", "laboratory", "use context"],
  },
  {
    path: "/safety-and-security",
    pageName: "Safety",
    pageTitle: "Safety and Security",
    group: "People",
    kind: "section",
    sectionTitle: "Hazards and controls",
    anchor: "hazards-and-controls",
    keywords: ["risk register", "hazard", "exposure", "residual risk"],
  },
  {
    path: "/safety-and-security",
    pageName: "Safety",
    pageTitle: "Safety and Security",
    group: "People",
    kind: "section",
    sectionTitle: "Approvals and documentation",
    anchor: "approvals-and-documentation",
    keywords: ["governance", "biosafety approval", "training", "waste management"],
  },

  // contribution.tsx
  {
    path: "/contribution",
    pageName: "Contribution",
    pageTitle: "Contribution",
    group: "People",
    kind: "section",
    sectionTitle: "Useful, documented, reusable",
    anchor: "useful-documented-reusable",
    keywords: ["for future teams", "resource", "usefulness", "access"],
  },
  {
    path: "/contribution",
    pageName: "Contribution",
    pageTitle: "Contribution",
    group: "People",
    kind: "section",
    sectionTitle: "What we are sharing",
    anchor: "what-we-are-sharing",
    keywords: ["contribution index", "sharing", "license", "validation"],
  },
  {
    path: "/contribution",
    pageName: "Contribution",
    pageTitle: "Contribution",
    group: "People",
    kind: "section",
    sectionTitle: "How another team can build on it",
    anchor: "how-another-team-can-build-on-it",
    keywords: ["reproducibility", "instructions", "prerequisites", "limitations"],
  },

  // team.tsx
  {
    path: "/team",
    pageName: "Team",
    pageTitle: "Our Team",
    group: "People",
    kind: "section",
    sectionTitle: "Strength comes from people",
    anchor: "strength-comes-from-people",
    keywords: ["our team", "captains", "members", "introductions"],
  },
  {
    path: "/team",
    pageName: "Team",
    pageTitle: "Our Team",
    group: "People",
    kind: "section",
    sectionTitle: "Guidance pending confirmation",
    anchor: "guidance-pending-confirmation",
    keywords: ["instructors", "advisors", "guidance", "consent"],
  },
  {
    path: "/team",
    pageName: "Team",
    pageTitle: "Our Team",
    group: "People",
    kind: "section",
    sectionTitle: "Credit must be precise",
    anchor: "credit-must-be-precise",
    keywords: ["attribution", "credit", "acknowledgements"],
  },
];

export default searchIndex;
