server {
    listen 80;
    server_name _;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /worldshaper-nanjing/;
    }

    location /worldshaper-nanjing/ {
        try_files $uri $uri/ /worldshaper-nanjing/index.html;
    }

    location / {
        return 404;
    }
}
