server {
    listen 80;
    server_name _;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /teamname/;
    }

    location /teamname/ {
        try_files $uri $uri/ /teamname/index.html;
    }

    location / {
        return 404;
    }
}
